### PR TITLE
OOP School Library: Associations

### PR DESCRIPTION
**Pull request by AmanWorku**
### Hello...

# Activities done: 
- [x] Created a class named `Classroom` with respective requirements.
- [x] Formed a relationship between `Classroom` and `Student` classes.
- [x] Created a class named `Book` that will be used to hold `title` and `author` of a book.
- [x] Created a class named `Rental` for holding rentals.
- [x] Formed a `many-to-many` relationship between `Person` and `Book` using the intermediate class `Rental`.

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Aman, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented, and all main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, only the _FAQ_ section is optional. Also, the _Future Features_ section of your ReadMe includes 1-3 potential features to be added later. You can discuss about expanding your project by adding more classes such as Music, Games, Movies, etc.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by frank1738 — COMMENTED** [review]
Hi @AmanWorku , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [x] As requested earlier, all headers are supposed to be in your readme file but the `key features` header is missing, kindly include it

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by youmari — APPROVED** [review]
# Project Approved :trophy: :tada: 🟢 

Hi @AmanWorku 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by AmanWorku** [comment]
@rloterh @youmari @frank1738  Thank you so much.

**Pull request merged**
